version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/react/
    overwrite: yes
permissions:
  - object: /usr/share/react/
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root